CALL NULLID.MRT_BP(1,5);

CALL NULLID.MRT_Connections_FMT_by_Row (1, 15);

CALL NULLID.MRT_DBSummary (1, 15);

CALL NULLID.MRT_Index (1, 5); 

CALL NULLID.MRT_IndexSUM (1, 5); 

CALL NULLID.MRT_Latch (1, 5); 

CALL NULLID.MRT_WorkloadDetXMLTIMES (1, 15); 

CALL NULLID.MRT_PkgCache (2, 3); 