/#
/*
CALL NULLID.MRT_TablesSUM (1, 10); 
*/
/********************************************************************************************************************************
*********************************************************************************************************************************

    Autor: Raul Diego
    E-mail: raul.oliveira@sicoob.com.br
    Data criação: 24/07/2015
    ->Descrição: MRT que faz a análise do comportamento das tabelas no momento. Nao mostra por partição. 
    ->Modo de execuçao: Crie a proc e a execute, informando o tempo de espera entre as execuçoes em segundos e quantas repetiçoes.
 
    Compatibilidade: DB2 LUW 10.1

    Histórico:
        - 00/00/0000: Historico de alteracao

        
*********************************************************************************************************************************
********************************************************************************************************************************/

CREATE OR REPLACE PROCEDURE NULLID.MRT_TablesSUM
     (IN v_Wait SMALLINT DEFAULT 5
     ,IN v_Repetition SMALLINT DEFAULT 3)
     
     LANGUAGE SQL
     RESULT SET 1

P1: BEGIN
 
    DECLARE v_RepetitionCount SMALLINT DEFAULT 1;
    
    DECLARE GLOBAL TEMPORARY TABLE SESSION.MRT_TablesSUM AS (
        SELECT T.TABSCHEMA, T.TABNAME
                , SUM(ROWS_READ) AS ROWS_READ, SUM(ROWS_INSERTED) AS ROWS_INSERTED, SUM(ROWS_UPDATED) AS ROWS_UPDATED, SUM(ROWS_DELETED) AS ROWS_DELETED
                , SUM(TABLE_SCANS) AS TABLE_SCANS, SUM(OVERFLOW_ACCESSES) AS OVERFLOW_ACCESSES, SUM(OVERFLOW_CREATES) AS OVERFLOW_CREATES
                , SUM(PAGE_REORGS) AS PAGE_REORGS, SUM(NO_CHANGE_UPDATES) AS NO_CHANGE_UPDATES
                , SUM(LOCK_WAIT_TIME) AS LOCK_WAIT_TIME, SUM(LOCK_WAIT_TIME_GLOBAL) AS LOCK_WAIT_TIME_GLOBAL, SUM(LOCK_WAITS) AS LOCK_WAITS
                        , SUM(LOCK_WAITS_GLOBAL) AS LOCK_WAITS_GLOBAL, SUM(LOCK_ESCALS) AS LOCK_ESCALS, SUM(LOCK_ESCALS_GLOBAL) AS LOCK_ESCALS_GLOBAL
                , SUM(DIRECT_WRITES) AS DIRECT_WRITES, SUM(DIRECT_WRITE_REQS) AS DIRECT_WRITE_REQS, SUM(DIRECT_READS) AS DIRECT_READS
                        , SUM(DIRECT_READ_REQS) AS DIRECT_READ_REQS
                , SUM(OBJECT_DATA_L_READS) AS OBJECT_DATA_L_READS, SUM(OBJECT_DATA_P_READS) AS OBJECT_DATA_P_READS, SUM(OBJECT_DATA_GBP_L_READS) AS OBJECT_DATA_GBP_L_READS
                , SUM(OBJECT_DATA_GBP_P_READS) AS OBJECT_DATA_GBP_P_READS, SUM(OBJECT_DATA_GBP_INVALID_PAGES) AS OBJECT_DATA_GBP_INVALID_PAGES
                , SUM(OBJECT_DATA_LBP_PAGES_FOUND) AS OBJECT_DATA_LBP_PAGES_FOUND, SUM(OBJECT_DATA_GBP_INDEP_PAGES_FOUND_IN_LBP) AS OBJECT_DATA_GBP_INDEP_PAGES_FOUND_IN_LBP
                , SUM(OBJECT_XDA_L_READS) AS OBJECT_XDA_L_READS, SUM(OBJECT_XDA_P_READS) AS OBJECT_XDA_P_READS
                , SUM(OBJECT_XDA_GBP_L_READS) AS OBJECT_XDA_GBP_L_READS, SUM(OBJECT_XDA_GBP_P_READS) AS OBJECT_XDA_GBP_P_READS, SUM(OBJECT_XDA_GBP_INVALID_PAGES) AS OBJECT_XDA_GBP_INVALID_PAGES
                , SUM(OBJECT_XDA_LBP_PAGES_FOUND) AS OBJECT_XDA_LBP_PAGES_FOUND
                , SUM(OBJECT_XDA_GBP_INDEP_PAGES_FOUND_IN_LBP) AS OBJECT_XDA_GBP_INDEP_PAGES_FOUND_IN_LBP, SUM(NUM_PAGE_DICT_BUILT) AS NUM_PAGE_DICT_BUILT
                ,CURRENT_TIMESTAMP AS DATAREGISTRO
                ,1 AS RepetitionCount 
        FROM TABLE(MON_GET_TABLE('','',-2)) AS T 
        WHERE T.TABSCHEMA NOT LIKE '%SYS%'
        GROUP BY T.TABSCHEMA, T.TABNAME
    ) DEFINITION ONLY
           ON COMMIT DELETE ROWS
           NOT LOGGED ON ROLLBACK DELETE ROWS
           WITH REPLACE;
         
    WHILE v_RepetitionCount <= v_Repetition DO
    
        INSERT INTO SESSION.MRT_TablesSUM
        SELECT T.TABSCHEMA, T.TABNAME
                , SUM(ROWS_READ) AS ROWS_READ, SUM(ROWS_INSERTED) AS ROWS_INSERTED, SUM(ROWS_UPDATED) AS ROWS_UPDATED, SUM(ROWS_DELETED) AS ROWS_DELETED
                , SUM(TABLE_SCANS) AS TABLE_SCANS, SUM(OVERFLOW_ACCESSES) AS OVERFLOW_ACCESSES, SUM(OVERFLOW_CREATES) AS OVERFLOW_CREATES
                , SUM(PAGE_REORGS) AS PAGE_REORGS, SUM(NO_CHANGE_UPDATES) AS NO_CHANGE_UPDATES
                , SUM(LOCK_WAIT_TIME) AS LOCK_WAIT_TIME, SUM(LOCK_WAIT_TIME_GLOBAL) AS LOCK_WAIT_TIME_GLOBAL, SUM(LOCK_WAITS) AS LOCK_WAITS
                        , SUM(LOCK_WAITS_GLOBAL) AS LOCK_WAITS_GLOBAL, SUM(LOCK_ESCALS) AS LOCK_ESCALS, SUM(LOCK_ESCALS_GLOBAL) AS LOCK_ESCALS_GLOBAL
                , SUM(DIRECT_WRITES) AS DIRECT_WRITES, SUM(DIRECT_WRITE_REQS) AS DIRECT_WRITE_REQS, SUM(DIRECT_READS) AS DIRECT_READS
                        , SUM(DIRECT_READ_REQS) AS DIRECT_READ_REQS
                , SUM(OBJECT_DATA_L_READS) AS OBJECT_DATA_L_READS, SUM(OBJECT_DATA_P_READS) AS OBJECT_DATA_P_READS, SUM(OBJECT_DATA_GBP_L_READS) AS OBJECT_DATA_GBP_L_READS
                , SUM(OBJECT_DATA_GBP_P_READS) AS OBJECT_DATA_GBP_P_READS, SUM(OBJECT_DATA_GBP_INVALID_PAGES) AS OBJECT_DATA_GBP_INVALID_PAGES
                , SUM(OBJECT_DATA_LBP_PAGES_FOUND) AS OBJECT_DATA_LBP_PAGES_FOUND, SUM(OBJECT_DATA_GBP_INDEP_PAGES_FOUND_IN_LBP) AS OBJECT_DATA_GBP_INDEP_PAGES_FOUND_IN_LBP
                , SUM(OBJECT_XDA_L_READS) AS OBJECT_XDA_L_READS, SUM(OBJECT_XDA_P_READS) AS OBJECT_XDA_P_READS
                , SUM(OBJECT_XDA_GBP_L_READS) AS OBJECT_XDA_GBP_L_READS, SUM(OBJECT_XDA_GBP_P_READS) AS OBJECT_XDA_GBP_P_READS, SUM(OBJECT_XDA_GBP_INVALID_PAGES) AS OBJECT_XDA_GBP_INVALID_PAGES
                , SUM(OBJECT_XDA_LBP_PAGES_FOUND) AS OBJECT_XDA_LBP_PAGES_FOUND
                , SUM(OBJECT_XDA_GBP_INDEP_PAGES_FOUND_IN_LBP) AS OBJECT_XDA_GBP_INDEP_PAGES_FOUND_IN_LBP, SUM(NUM_PAGE_DICT_BUILT) AS NUM_PAGE_DICT_BUILT
                ,CURRENT_TIMESTAMP AS DATAREGISTRO
                ,v_RepetitionCount AS RepetitionCount 
        FROM TABLE(MON_GET_TABLE('','',-2)) AS T 
        WHERE T.TABSCHEMA NOT LIKE '%SYS%'
        GROUP BY T.TABSCHEMA, T.TABNAME;
    
        SET v_RepetitionCount = v_RepetitionCount + 1;
        
        --CALL NULLID.WAITFOR(v_Wait);
        CALL NULLID.WAITFOR_MRT(v_Wait, 'MRT_TablesSUM');

    END WHILE;    
    
P2: BEGIN

    DECLARE cRet CURSOR WITH RETURN FOR
        WITH C AS (
        SELECT T2.TABSCHEMA, T2.TABNAME
                , T2.ROWS_READ - T1.ROWS_READ AS ROWS_READ
                , T2.ROWS_INSERTED - T1.ROWS_INSERTED AS ROWS_INSERTED
                , T2.ROWS_UPDATED - T1.ROWS_UPDATED AS ROWS_UPDATED
                , T2.ROWS_DELETED - T1.ROWS_DELETED AS ROWS_DELETED
                , T2.TABLE_SCANS - T1.TABLE_SCANS AS TABLE_SCANS
                , T2.OVERFLOW_ACCESSES - T1.OVERFLOW_ACCESSES AS OVERFLOW_ACCESSES
                , T2.OVERFLOW_CREATES - T1.OVERFLOW_CREATES AS OVERFLOW_CREATES
                , T2.OBJECT_DATA_L_READS - T1.OBJECT_DATA_L_READS AS OBJECT_DATA_L_READS
                , T2.OBJECT_DATA_P_READS - T1.OBJECT_DATA_P_READS AS OBJECT_DATA_P_READS
                , T2.OBJECT_XDA_L_READS - T1.OBJECT_XDA_L_READS AS OBJECT_XDA_L_READS
                , T2.OBJECT_XDA_P_READS - T1.OBJECT_XDA_P_READS AS OBJECT_XDA_P_READS
                , T2.LOCK_WAIT_TIME - T1.LOCK_WAIT_TIME AS LOCK_WAIT_TIME
                , T2.LOCK_WAIT_TIME_GLOBAL - T1.LOCK_WAIT_TIME_GLOBAL AS LOCK_WAIT_TIME_GLOBAL
                , T2.LOCK_WAITS - T1.LOCK_WAITS AS LOCK_WAITS
                , T2.LOCK_WAITS_GLOBAL - T1.LOCK_WAITS_GLOBAL AS LOCK_WAITS_GLOBAL
                , T2.LOCK_ESCALS - T1.LOCK_ESCALS AS LOCK_ESCALS
                , T2.LOCK_ESCALS_GLOBAL - T1.LOCK_ESCALS_GLOBAL AS LOCK_ESCALS_GLOBAL
                , T2.PAGE_REORGS - T1.PAGE_REORGS AS PAGE_REORGS
                , T2.NO_CHANGE_UPDATES - T1.NO_CHANGE_UPDATES AS NO_CHANGE_UPDATES
                , T2.DIRECT_WRITES - T1.DIRECT_WRITES AS DIRECT_WRITES
                , T2.DIRECT_WRITE_REQS - T1.DIRECT_WRITE_REQS AS DIRECT_WRITE_REQS
                , T2.DIRECT_READS - T1.DIRECT_READS AS DIRECT_READS
                , T2.DIRECT_READ_REQS - T1.DIRECT_READ_REQS AS DIRECT_READ_REQS
                , T2.DATAREGISTRO
                , T2.REPETITIONCOUNT
        --, OBJECT_DATA_GBP_L_READS, OBJECT_DATA_GBP_P_READS
        --, OBJECT_DATA_GBP_INVALID_PAGES, OBJECT_DATA_LBP_PAGES_FOUND, OBJECT_DATA_GBP_INDEP_PAGES_FOUND_IN_LBP, OBJECT_XDA_L_READS, OBJECT_XDA_P_READS
        --, OBJECT_XDA_GBP_L_READS, OBJECT_XDA_GBP_P_READS, OBJECT_XDA_GBP_INVALID_PAGES, OBJECT_XDA_LBP_PAGES_FOUND, OBJECT_XDA_GBP_INDEP_PAGES_FOUND_IN_LBP, NUM_PAGE_DICT_BUILT
        FROM SESSION.MRT_TablesSUM T1
        LEFT JOIN SESSION.MRT_TablesSUM T2 
                ON T1.TABSCHEMA = T2.TABSCHEMA
                AND T1.TABNAME = T2.TABNAME
                AND T1.RepetitionCount < T2.RepetitionCount
                AND T2.RepetitionCount - T1.RepetitionCount = 1
        )
        SELECT TO_CHAR(C.DATAREGISTRO,'HH24:MI:SS') AS Horario
        ,C.*
        ,'REP' || C.REPETITIONCOUNT AS RepetitionCount
        FROM C
        WHERE TABSCHEMA IS NOT NULL  
        AND (ROWS_READ <> 0 OR ROWS_INSERTED <> 0 OR ROWS_UPDATED <> 0 OR ROWS_DELETED <> 0 OR TABLE_SCANS <> 0 
                OR OVERFLOW_ACCESSES <> 0 OR  OVERFLOW_CREATES <> 0 OR OBJECT_DATA_L_READS <> 0 OR OBJECT_DATA_P_READS <> 0 
                OR OBJECT_XDA_L_READS <> 0 OR OBJECT_XDA_P_READS <> 0 OR  LOCK_WAIT_TIME <> 0 OR LOCK_WAIT_TIME_GLOBAL <> 0 
                OR LOCK_WAITS <> 0 OR LOCK_WAITS_GLOBAL <> 0 OR LOCK_ESCALS <> 0 OR PAGE_REORGS <> 0 OR  DIRECT_WRITES <> 0 
                OR DIRECT_WRITE_REQS <> 0 OR DIRECT_READS <> 0 OR DIRECT_READ_REQS <> 0
             )
        ORDER BY HORARIO, TABSCHEMA, TABNAME
        --ORDER BY HORARIO, ROWS_READ
        ;
    
    OPEN cReT;
    
END P2;
END P1

/*
CALL NULLID.MRT_TablesSUM ();
CALL NULLID.MRT_TablesSUM (1, 4); 
*/
#/    


